version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    container_name: web-app
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    env_file: 
      - .env
    volumes: 
      - pg-data:/var/lib/postgresql/data
volumes: 
  pg-data:
    driver: local 